pipeline {
    agent any
    stages {
        stage('Code') {
            steps {
                echo "Cloning the code"
                git credentialsId: 'user-git', branch: 'main', url: 'https://github.com/pedropenhavn/Customer_Service'
            }
        }
        stage('Copy Env File') {
            steps {
                script {
                    withCredentials([file(credentialsId: 'customer-service.env', variable: 'ENV_FILE')]) {
                        sh "cp '${ENV_FILE}' /var/lib/jenkins/workspace/customer-service/.env"
                        sh "chmod 775 /var/lib/jenkins/workspace/customer-service/.env"
                    }
                }
            }
        }
        stage('Build and Run Docker') {
            steps {
                script {
                    sh 'docker compose down'
                    sh 'docker compose up -d --build'
                }
            }
        }
    }
}

