[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/log/supervisor/supervisord.pid

[program:octane-start]
command=php artisan serve --host=0.0.0.0 --port=8000
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/octane.log
stderr_logfile=/var/log/supervisor/octane_err.log


