[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/log/supervisor/supervisord.pid

[program:octane-start]
command=php artisan octane:start --host=0.0.0.0 --port=8000 --workers=24 --task-workers=12
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/octane.log
stderr_logfile=/var/log/supervisor/octane_err.log

[program:schedule-run]
command=sh -c "while :; do php /var/www/artisan schedule:run --verbose --no-interaction; sleep 60; done"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/schedule.log
stderr_logfile=/var/log/supervisor/schedule_err.log

[program:queue-assortments-unavailable-create]
command=/usr/local/bin/php /var/www/artisan queue:work --queue=assortments_unavailable_create
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/schedule.log
stderr_logfile=/var/log/supervisor/schedule_err.log

[program:queue-assortments-unavailable-delete]
command=/usr/local/bin/php /var/www/artisan queue:work --queue=assortments_unavailable_delete
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/schedule.log
stderr_logfile=/var/log/supervisor/schedule_err.log
