[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/log/supervisor/supervisord.pid

[program:laravel-server]
command=php artisan serve --host=0.0.0.0 --port=8000
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/laravel.log
stderr_logfile=/var/log/supervisor/laravel_err.log

[program:schedule-run]
command=sh -c "while :; do php /var/www/artisan schedule:run --verbose --no-interaction; sleep 60; done"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/schedule.log
stderr_logfile=/var/log/supervisor/schedule_err.log
